-- 16/08/2026 — TOTP-based two-factor authentication.
--
-- Numbered 0091, not 0086: migrations/demo_registry/ (a SEPARATE database,
-- with its own schema_migrations) already uses 0086-0090 — those can never
-- collide with this directory's own numbering, but skipping past them keeps
-- `ls migrations/*.sql` unambiguous for a human scanning both directories at
-- once. Every statement below is unqualified (no "public." prefix) so it
-- replays correctly into each demo slot's own schema, exactly like every
-- other migration in this directory — see internal/db/migrate.go and
-- internal/demo/manager.go's per-slot search_path.
--
-- Storage split across three places:
--
--   users.totp_secret_enc / totp_pending_secret_enc
--     XChaCha20-Poly1305 ciphertext (internal/pii), key TOTP_ENC_KEY —
--     DELIBERATELY SEPARATE from PII_ENC_KEY and TA_DOCS_ENC_KEY, so leaking
--     one key never leaks the others. AAD is the user's own id, so a
--     ciphertext copied onto a different row fails to decrypt. TWO columns,
--     not one: "pending" holds the secret shown on the enrolment QR code
--     until the user proves they scanned it; "secret_enc" is the live secret
--     actually checked at login. Writing straight into secret_enc during
--     setup would silently invalidate an already-working authenticator the
--     moment a user re-opens the setup page — this is a real self-lockout,
--     not a hypothetical one. Enable() is the only thing that promotes
--     pending -> live, and only after verifying a code against pending.
--   totp_key_version
--     Which TOTP_ENC_KEY encrypted totp_secret_enc, mirroring
--     ta_profiles.citizen_id_key_version, for future key rotation.
--   totp_enabled_at
--     NULL = 2FA off. Non-NULL is what AccountGuard checks to enforce
--     mandatory enrolment for admin/staff/executive accounts.
--   totp_last_step
--     The Unix time-step of the most recently ACCEPTED code. A TOTP code is
--     valid for a ~30s window, so without this a code sniffed once could be
--     replayed for the rest of that window. Written in the same transaction
--     that creates the session, so it also closes the race between two
--     concurrent requests presenting the same still-valid code.
--
--   mfa_recovery_codes
--     One-time codes issued 10-at-a-time whenever 2FA is enabled or
--     regenerated. Stored as a plain SHA-256 hash (not bcrypt): these are
--     128-bit random values, not user-chosen secrets, so there is no
--     dictionary to defend against and no reason to pay bcrypt's per-compare
--     cost — a single indexed lookup on (user_id, code_hash) is both correct
--     and constant-time by construction, unlike iterating a user's rows.
--
--   mfa_challenges
--     The "you got the password right, now prove the second factor" ticket
--     issued by step 1 of login. token_hash is a SHA-256 of an opaque
--     32-byte value handed to the client — the client's copy is the only
--     plaintext copy anywhere. attempts is bumped and checked in ONE
--     UPDATE ... WHERE attempts < 5 RETURNING statement (see
--     internal/handler/auth.go), never read-then-written, so two concurrent
--     guesses can't both slip through under the cap. consumed_at makes a
--     challenge single-use even within its own 5-attempt/5-minute budget.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS totp_secret_enc BYTEA,
    ADD COLUMN IF NOT EXISTS totp_pending_secret_enc BYTEA,
    ADD COLUMN IF NOT EXISTS totp_key_version SMALLINT,
    ADD COLUMN IF NOT EXISTS totp_enabled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS totp_last_step BIGINT;

COMMENT ON COLUMN users.totp_secret_enc IS
    'XChaCha20-Poly1305 ciphertext of the live TOTP secret: [24B nonce][ciphertext+16B tag]. Key = TOTP_ENC_KEY (internal/pii), AAD = user_id. NULL until 2FA is enabled. Never returned by any API.';
COMMENT ON COLUMN users.totp_pending_secret_enc IS
    'Same encoding as totp_secret_enc, but for a secret generated by /me/2fa/setup that has not yet been confirmed by /me/2fa/enable. Cleared once promoted (or abandoned).';
COMMENT ON COLUMN users.totp_key_version IS
    'Which TOTP_ENC_KEY version encrypted totp_secret_enc, for key rotation.';
COMMENT ON COLUMN users.totp_enabled_at IS
    'NULL = 2FA disabled. Set when totp_pending_secret_enc is promoted to totp_secret_enc. AccountGuard enforces mandatory enrolment for admin/staff/executive accounts on this column.';
COMMENT ON COLUMN users.totp_last_step IS
    'Unix time-step (unix_seconds / 30) of the most recently accepted TOTP code. Rejects replay of a still-valid code within its ~30s window.';

CREATE TABLE mfa_recovery_codes (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash  BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at    TIMESTAMPTZ,
    UNIQUE (user_id, code_hash)
);

COMMENT ON TABLE mfa_recovery_codes IS
    'One-time backup codes for logging in without the TOTP device. Issued 10 at a time on enable/regenerate; each row is burned exactly once via an atomic UPDATE ... WHERE used_at IS NULL.';

-- The lookup on login: "does this user have an unused code matching this
-- hash". The UNIQUE constraint above already gives this shape an index, but
-- this one is scoped to unused rows only, matching the access pattern.
CREATE INDEX ix_mfa_recovery_codes_unused ON mfa_recovery_codes (user_id, code_hash) WHERE used_at IS NULL;

CREATE TABLE mfa_challenges (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  BYTEA NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL,
    attempts    INT NOT NULL DEFAULT 0,
    consumed_at TIMESTAMPTZ
);

COMMENT ON TABLE mfa_challenges IS
    'Issued by step 1 of login (password verified, TOTP pending) and redeemed by POST /auth/login/2fa. 5-minute TTL, 5-attempt cap enforced by a single atomic UPDATE, single-use via consumed_at. Swept by the daily scheduler alongside sessions.';

-- The redemption lookup: find this exact challenge by its token's hash.
-- token_hash already being UNIQUE gives this an index; this scopes it to
-- live challenges, matching the query AccountGuard's sibling would run.
CREATE INDEX ix_mfa_challenges_live ON mfa_challenges (token_hash) WHERE consumed_at IS NULL;

-- The cleanup sweep's own lookup, same shape as ix_sessions_last_activity.
CREATE INDEX ix_mfa_challenges_expires ON mfa_challenges (expires_at);
